config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'mains#index'

  resources :mains, only:[:index]
  resources :places do
    resources :comments, only:[:create]
  end
end

app/models/place.rb
class Place < ApplicationRecord
  with_options presence: true do
    validates :image
    validates :name
    validates :info
    validates :category_id, numericality: { other_than: 1 ,message:"Select" }
    validates :country_id, numericality: { other_than: 1 ,message:"Select" }
  end

  has_one_attached :image
  belongs_to :user
  has_many :comments, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :country

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :place_find, only: [:show, :edit, :update, :destroy]

  def index
    @places = Place.includes(:user).order("id DESC")
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.valid?
      @place.save
      redirect_to places_path
    else
      render action: :new
    end
  end

  def show
    @comments = Comment.all
    @comment = Comment.new
  end

  def edit
    redirect_to root_path if current_user.id != @place.user_id 
  end

  def update
    if @place.update(place_params)
      redirect_to @place
    else
      render action: :edit
    end
  end

  def destroy
    if current_user.id == @place.user_id
      @place.destroy
      redirect_to places_path
    else
      redirect_to places_path
    end
  end

  private
    def place_params
      params.require(:place).permit(:image, :name, :info, :category_id, :country_id).merge(user_id: current_user.id)
    end

    def place_find
      @place = Place.find(params[:id])
    end
    
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/edit.html.erb
    <!-- Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="../../assets/logo/loder.jpg" alt="">
                </div>
            </div>
        </div>
    </div>

    <%#投稿する内容の入力%>
    <main>
      <div class="mains-sell-contents">
        <div class="mains-sell-main">
        <h1 class="mains-sell-title">お気に入りの場所を投稿</h1>
  
        <%= form_with( model: @place, local: true) do |f| %>
        <%= render 'shared/error_messages', model: f.object %>
      <%# 投稿画像 %>
          <div class="img-upload">
            <div class="weight-bold-text">
              出品画像
            <span class="indispensable">必須</span>
            </div>
            <div class="click-upload">
              クリックしてファイルをアップロード
            </div>
              <%= f.file_field :image %>
          </div>
      <%# 場所と場所の詳細 %>
          <div class="weight-bold-text">
            場所
            <span class="indispensable">必須</span>
          </div>
  
          <%= f.text_area :name, class:"single-input-primary", placeholder:"場所の名前（必須 20文字まで)", maxlength:"20" %>
  
          <div class="weight-bold-text">
            <div class="info-text">
              場所の詳細
            <span class="indispensable">必須</span>
            </div>
          </div>
  
          <%= f.text_area :info, class:"single-input-primary", placeholder:"どんな場面なのか詳細を書いてみよう。(200文字まで)" ,rows:"7" ,maxlength:"200" %>

          <div class="category_country">
            <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"category"}) %>
            <%= f.collection_select(:country_id, Country.all, :id, :name, {}, {class: "country"}) %>
          </div>
      <%# 下部ボタン %>
          <div class="sell-btn-contents">
            <%= f.submit "変更する" ,class:"sell-btn" %>
            <%=link_to 'もどる', place_path, class:"back-btn" %>
          </div>
        <% end %>
        </div>
      </div>
    </main>

app/views/places/index.html.erb
    <!-- Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="../../assets/logo/loder.jpg" alt="">
                </div>
            </div>
        </div>
    </div>

    <!-- Preloader Start -->
    <header>
        <!-- Header Start -->
       <div class="header-area header-transparent">
            <div class="main-header">
               <div class="header-bottom  header-sticky">
                    <div class="container-fluid">
                        <div class="row align-items-center">
                            <!-- Logo -->
                            <div class="col-xl-2 col-lg-2 col-md-1">
                                <div class="logo">
                                  <%= link_to image_tag("logo/logo.png"), root_path %>
                                </div>
                            </div>
                            <div class="col-xl-10 col-lg-10 col-md-8">
                                <!-- Main-menu -->
                                <div class="main-menu f-right d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">                                                                                                                                     
                                            <li><%= link_to 'Home',root_path %></li>
                                            <li><%= link_to 'Posted page',places_path %></li>
                                            <li class="login">
                                                <% if user_signed_in? %>
                                                    <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
                                                    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "logout" %></li>
                                                <% else %>
                                                    <li><%= link_to 'Login', new_user_session_path, class: "login" %></li>
                                                    <li><%= link_to 'Sign up', new_user_registration_path, class: "sign-up" %></li>
                                                <% end %>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <!-- Mobile Menu -->
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>
               </div>
            </div>
       </div>
        <!-- Header End -->
    </header>

    <main>
      <!-- Hero Area Start-->
        <div class="slider-area hero-overly">
            <div class="single-slider hero-overly  slider-height d-flex align-items-center">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-xl-8 col-lg-9">
                            <!-- Hero Caption -->
                            <div class="hero__caption">
                                <span>Posts List</span>
                                <h1>Discover Great Places</h1>
                            </div>	
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--Hero Area End-->
<!-------------------------------------------------------------------------------------------------------------------------------------------------------->
        <div class="place-content-item">
          <ul>
            <% if @places.length != 0 %>
              <% @places.each do |place| %>
                <%= link_to place_path(place) do %>
                <li class='list2'>
                    <%= image_tag place.image,class: 'place-image' if place.image.attached? %>
                    <div class='place-text'>
                      <h3 class='place-name'><%= place.name %></h3>
                      <div class='place-info'><%= place.info %></div>
                    </div>
                </li>
                <% end %>
              <% end %>
            <% else %>
                <%= link_to '#' do %>
                <li class='list2'>
                    <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "place-image" %>
                    <div class='place-text'>
                      <h3 class='place-name'>投稿してね！</h3>
                    </div>
                </li>
                <% end %>
            <% end %>
          </ul>
        </div>
<!------------------------------------------------------------------------------------------------------------------------------------------------------------->
    </main>

     <footer>
        <!-- Footer Start-->
        <div class="footer-area">
            <div class="container">
               <div class="footer-top footer-padding">
                    <div class="row justify-content-between">
                        <div class="col-xl-3 col-lg-4 col-md-4 col-sm-6">
                            <div class="single-footer-caption mb-50">
                                <div class="single-footer-caption mb-30">
                                    <!-- logo -->
                                    <div class="footer-logo">
                                        <%= link_to image_tag("logo/logo.png"), root_path %>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-2 col-lg-2 col-md-4 col-sm-6">
                            <div class="single-footer-caption mb-50">
                                <div class="footer-tittle">
                                    <h4>Quick Link</h4>
                                    <ul>
                                        <li><%= link_to 'Home',root_path %></li>
                                        <li><%= link_to 'Posted page',places_path %></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6">
                            <div class="single-footer-caption mb-50">
                                <div class="footer-tittle">
                                    <h4>Categories</h4>
                                    <ul>
                                        <li><a href="#">Reasonable Hotel</a></li>
                                        <li><a href="#">Popular Restaurant</a></li>
                                        <li><a href="#">Easy Shopping</a></li>
                                        <li><a href="#">Night Life</a></li>     
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                            <div class="single-footer-caption mb-50">
                                <div class="footer-tittle">
                                </div>
                            </div>
                        </div>
                    </div>
               </div>
                <div class="footer-bottom">
                    <div class="row d-flex justify-content-between align-items-center">
                        <div class="col-xl-9 col-lg-8">
                            <div class="footer-copy-right">
                                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-4">
                            <!-- Footer Social -->
                            <div class="footer-social f-right">
                                <a href="#"><i class="fab fa-facebook-f"></i></a>
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="#"><i class="fas fa-globe"></i></a>
                                <a href="#"><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
               </div>
            </div>
        </div>
        <!-- Footer End-->
    </footer>

    <div class='purchase-btn'>
      <span class='purchase-btn-text'>投稿する</span>
      <%= link_to image_tag("camera.png", size: '185x50' ,class: "purchase-btn-icon"), new_place_path %>
    </div>

app/views/places/new.html.erb
<!-- Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="../../assets/logo/loder.jpg" alt="">
                </div>
            </div>
        </div>
    </div>

    <%#投稿する内容の入力%>
    <main>
      <div class="mains-sell-contents">
        <div class="mains-sell-main">
        <h1 class="mains-sell-title">お気に入りの場所を投稿</h1>
  
        <%= form_with model: @place, local: true do |f| %>
        <%= render 'shared/error_messages', model: f.object %>
      <%# 投稿画像 %>
          <div class="img-upload">
            <div class="weight-bold-text">
              出品画像
            <span class="indispensable">必須</span>
            </div>
            <div class="click-upload">
              クリックしてファイルをアップロード
            </div>
              <%= f.file_field :image %>
          </div>
      <%# 場所と場所の詳細 %>
          <div class="weight-bold-text">
            場所
            <span class="indispensable">必須</span>
          </div>
  
          <%= f.text_area :name, class:"single-input-primary", placeholder:"場所の名前（必須 20文字まで)", maxlength:"20" %>
  
          <div class="weight-bold-text">
            <div class="info-text">
              場所の詳細
            <span class="indispensable">必須</span>
            </div>
          </div>
  
          <%= f.text_area :info, class:"single-input-primary", placeholder:"どんな場面なのか詳細を書いてみよう。(200文字まで)" ,rows:"7" ,maxlength:"200" %>

          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class: "category"}) %>

          <%= f.collection_select(:country_id, Country.all, :id, :name, {}, {class: "country"}) %>
          
      <%# 下部ボタン %>
          <div class="sell-btn-contents">
            <%= f.submit "投稿する" ,class:"sell-btn" %>
            <%=link_to 'もどる', root_path, class:"back-btn" %>
          </div>
        <% end %>
        </div>
      </div>
    </main>

app/views/places/show.html.erb
    <!-- Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="../../assets/logo/loder.jpg" alt="">
                </div>
            </div>
        </div>
    </div>

    <!-- Preloader Start -->
    <header>
        <!-- Header Start -->
       <div class="header-area header-transparent">
            <div class="main-header">
               <div class="header-bottom  header-sticky">
                    <div class="container-fluid">
                        <div class="row align-items-center">
                            <!-- Logo -->
                            <div class="col-xl-2 col-lg-2 col-md-1">
                                <div class="logo">
                                  <%= link_to image_tag("logo/logo.png"), root_path %>
                                </div>
                            </div>
                            <div class="col-xl-10 col-lg-10 col-md-8">
                                <!-- Main-menu -->
                                <div class="main-menu f-right d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">                                                                                                                                     
                                            <li><%= link_to 'Home',root_path %></li>
                                            <li><%= link_to 'Posted page',places_path %></li>
                                            <li class="login">
                                                <% if user_signed_in? %>
                                                    <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
                                                    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "logout" %></li>
                                                <% else %>
                                                    <li><%= link_to 'Login', new_user_session_path, class: "login" %></li>
                                                    <li><%= link_to 'Sign up', new_user_registration_path, class: "sign-up" %></li>
                                                <% end %>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <!-- Mobile Menu -->
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>
               </div>
            </div>
       </div>
        <!-- Header End -->
    </header>
    <main>
      <!-- Hero Area Start-->
        <div class="slider-area hero-overly">
            <div class="single-slider hero-overly  slider-height d-flex align-items-center">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-xl-8 col-lg-9">
                            <!-- Hero Caption -->
                            <div class="hero__caption">
                                <span>Posts List</span>
                                <h1>Discover Great Places</h1>
                            </div>	
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--Hero Area End-->
<!--------------------------------------------------------->
      <div class="place-show">
        <div class="place-box">
          <h2 class="name">
            <%= @place.name %>
          </h2>
          <div class='place-img-content'>
            <%= image_tag @place.image ,class:"place-box-img" %>
          </div>

          <% if user_signed_in?  %>
            <% if current_user.id == @place.user_id %>
              <%= link_to '投稿の編集', edit_place_path, method: :get, class: "place-red-btn" %>
              <p class='or-text'>or</p>
              <%= link_to '投稿の削除', place_path, method: :delete, class:'place-destroy' %>
            <% end %>
          <% end %>
      
          <div class="place-explain-box">
            <span><%= @place.info %></span>
          </div>
          <table class="detail-table">
            <tbody>
              <tr>
                <th class="detail-place">カテゴリー</th>
                <td class="detail-value"><%= @place.category.name %></td>
              </tr>
              <tr>
                <th class="detail-place">国名</th>
                <td class="detail-value"><%= @place.country.name %></td>
              </tr>
            </tbody>
          </table>
          <div class="option">
            <div class="favorite-btn">
              <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
              <span>お気に入り 0</span>
            </div>
            <div class="report-btn">
              <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
              <span>不適切な商品の通報</span>
            </div>
          </div>
        </div>

        <%= form_with(model:[@place, @comment], class: "comment-box", local: true) do |f| %>
          <div id='comments'>
          <% @comments.each do |comment| %>
            <% if @place.id == comment.place_id %>
            <p><%= comment.user.nickname %>:<%= comment.text %></p>
            <% end %>
          <% end %>
          </div>
        
          <%= f.text_area :text, class:"comment-text" %>
        
          <p class="comment-warn">
            相手のことを考え丁寧なコメントを心がけましょう。
            <br>
            不快な言葉遣いなどは利用制限や退会処分となることがあります。
          </p>
          <button type="submit" class="comment-btn">
            <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
            <span>コメントする<span>
          </button>
        <% end %>

      </main>
<!------------------------------------------------------------->
      <footer>
        <!-- Footer Start-->
        <div class="footer-area">
            <div class="container">
               <div class="footer-top footer-padding">
                    <div class="row justify-content-between">
                        <div class="col-xl-3 col-lg-4 col-md-4 col-sm-6">
                            <div class="single-footer-caption mb-50">
                                <div class="single-footer-caption mb-30">
                                    <!-- logo -->
                                    <div class="footer-logo">
                                        <%= link_to image_tag("logo/logo.png"), root_path %>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-2 col-lg-2 col-md-4 col-sm-6">
                            <div class="single-footer-caption mb-50">
                                <div class="footer-tittle">
                                    <h4>Quick Link</h4>
                                    <ul>
                                        <li><%= link_to 'Home',root_path %></li>
                                        <li><%= link_to 'Posted page',places_path %></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6">
                            <div class="single-footer-caption mb-50">
                                <div class="footer-tittle">
                                    <h4>Categories</h4>
                                    <ul>
                                        <li><a href="#">Reasonable Hotel</a></li>
                                        <li><a href="#">Popular Restaurant</a></li>
                                        <li><a href="#">Easy Shopping</a></li>
                                        <li><a href="#">Night Life</a></li>     
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                            <div class="single-footer-caption mb-50">
                                <div class="footer-tittle">
                                </div>
                            </div>
                        </div>
                    </div>
               </div>
                <div class="footer-bottom">
                    <div class="row d-flex justify-content-between align-items-center">
                        <div class="col-xl-9 col-lg-8">
                            <div class="footer-copy-right">
                                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-4">
                            <!-- Footer Social -->
                            <div class="footer-social f-right">
                                <a href="#"><i class="fab fa-facebook-f"></i></a>
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="#"><i class="fas fa-globe"></i></a>
                                <a href="#"><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
               </div>
            </div>
        </div>
        <!-- Footer End-->
    </footer>

    <div class='purchase-btn'>
      <span class='purchase-btn-text'>投稿する</span>
      <%= link_to image_tag("camera.png", size: '185x50' ,class: "purchase-btn-icon"), new_place_path %>
    </div>